### ISSUE TITLE
Facebook link not going to correct page

### ISSUE THREAD

**Issue by abrowne2** [gatesyp/dh-landing#10]
At the bottom of index.html, facebook has the wrong link.

It should be:
`https://www.facebook.com/deephire.io/`
but it's:
`https://www.facebook.com/deephire/` , redirecting to deep.hire

**Comment by RusseII** [comment]
Nice catch. Fixed https://github.com/gatesyp/dh-landing/commit/3b73bb379ac3635d65ebc46229ba24e6a2b363ea
