### ISSUE TITLE
Navbar buttons disappear after clicking

### ISSUE THREAD

**Issue by emersoncloud** [gatesyp/dh-landing#2]
The navbar buttons can't be seen or clicked after the first click.

![image](https://user-images.githubusercontent.com/13784188/38212931-8e8b2810-368d-11e8-8057-c0785cc1c59f.png)

![image](https://user-images.githubusercontent.com/13784188/38212937-96e219d8-368d-11e8-99f8-7b61e383d288.png)

**Comment by gatesyp** [comment]
Thanks! Fixed in the latest update
